### PR TITLE
Fix S107: Do not raise for P/Invoke methods (#1459)

### PR DESCRIPTION
**Pull request by lukas-ais**

### CODE REVIEW

**Comment by duncanp-sonar** [comment]
Thanks @lukas-ais!

FYI this fix will ship in the next release of the analyzer, which we're aiming to do next week or the first week in July.

**Comment by lukas-ais** [comment]
Hi @duncanp-sonar 

I was wondering why the CI build was not started/completed for about 24 hours. Is this normal? Do I have to do anything else to get the build running?

Do we need any changes on the any other part of SonarQube? According to the contributors document there is a difference between "plugin" and "analyzer".

**Comment by valhristov** [comment]
The CI works only for PRs initiated from the sonar-csharp repository. Otherwise someone could commit script that does bad things to the build machines (formats hard drive, downloads viruses, etc.) that will be automatically executed when a PR is opened.

**Comment by duncanp-sonar** [comment]
@lukas-ais The "plugin" is the Java part of the handles the interaction with SonarQube.
The rules are completely in the C# analyzer part, so since you just changed a rule then there is nothing else to do.

**Pull request merged**
