### PR TITLE
Support NUnit 3

### PR DESCRIPTION
**Pull request by lahma**
Now NUnitTestResultsFileParser detects which format is in use and also can parse results from the new NUnit3 fomat. The sample file is the one [provided by the NUnit3 project](http://nunit.org/files/testresult_30.txt).

### CODE REVIEW

**Comment by Evangelink** [comment]
Hi @lahma,

Thanks for this PR. We will have a look at it tomorrow.

**Comment by lahma** [comment]
I actually had to change their sample to have `duration` attribute instead of `time` attribute for test-run element so that their sample would conform to [their spec](https://github.com/nunit/docs/wiki/Test-Result-XML-Format) (and the actual result files that runner outputs).

**Comment by Evangelink** [comment]
Hi @lahma ,

I couldn't merge this PR directly because we have a security to prevent merging PR if the build is not working and another one to prevent build from PR from outside so I had to create another PR (#715) which I merged to master.
No worries you remain the author of the commit.

Cheers,
Amaury

**Comment by lahma** [comment]
All is good, thank you for bringing this in!

**Comment by Evangelink** [comment]
@lahma just reopened and merged again (I guess I squashed instead of rebase).

**Pull request closed without merging**
