### PR TITLE
Add a .gitattributes file

### PR DESCRIPTION
**Pull request by Evangelink**

### CODE REVIEW

**Comment by michalb-sonar** [comment]
Looks good and it is a great idea. However I had some problems when following suggestions from that link. Will run few more tests.

FYI, this was one of the tests: https://github.com/SonarSource/sonar-csharp/blob/fix-nl/.gitattributes

**Comment by Evangelink** [comment]
@michalb-sonar Any news on this?

**Comment by michalb-sonar** [comment]
@Evangelink not yet, but I keep this in mind. Will do it before we finish current sprint and go back to sonar-csharp (and hopefully much sooner)

**Comment by Evangelink** [comment]
Closing PR then.

**Pull request closed without merging**
